version: 0.1

phases:
  install:
    commands:
    - echo Installing source NPM dependencies...
    - npm install
    - npm install -g @angular/cli
  build:
    commands:
    - echo Build started on `date`
    - ng build --prod
  post_build:
    commands:
    - aws s3 cp dist s3://checkers-prod-resources --recursive
artifacts:
  files:
  - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
