version: 0.1

phases:
  build:
    commands:
    - echo Installing source NPM dependencies...
    - npm install
    - npm install -g @angular/cli
    - ng build --prod
artifacts:
  files:
  - '**/*'
  base-directory: 'dist*'
  discard-paths: no

cache:
  paths:
  - 'node_modules/**/*'

